# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c83e0899a2f8ca3ceb516c635f12e3602ab6b0426dcf6f30dcb1afce6948491187490b1d6e3360b3ce4185f955827c6d752a35950c49bafda81eda4323b52f7e

test:
  secret_key_base: f0d6c000d489665bb613a137226280145bd6ec4775827f14a8a77b3f0fb08a9f9c0a777ed2f8799f8436c529013918b0785c8779dbce4aff515d0d5cd54b52f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
